//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPrivacyMicroservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActorRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActorRole()
        {
            this.ActorRolePersonalDataFields = new HashSet<ActorRolePersonalDataField>();
            this.ActorRolePurposes = new HashSet<ActorRolePurpose>();
            this.PersonalDataActorRoles = new HashSet<PersonalDataActorRole>();
        }
    
        public int id { get; set; }
        public int actorID { get; set; }
        public int roleID { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActorRolePersonalDataField> ActorRolePersonalDataFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActorRolePurpose> ActorRolePurposes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalDataActorRole> PersonalDataActorRoles { get; set; }
    }
}
