//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPrivacyMicroservice.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataPrivacyEntities : DbContext
    {
        public DataPrivacyEntities()
            : base("name=DataPrivacyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<ActorRole> ActorRoles { get; set; }
        public virtual DbSet<ActorRolePersonalDataField> ActorRolePersonalDataFields { get; set; }
        public virtual DbSet<ActorRolePurpose> ActorRolePurposes { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<PersonalData> PersonalDatas { get; set; }
        public virtual DbSet<PersonalDataField> PersonalDataFields { get; set; }
        public virtual DbSet<Purpose> Purposes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolePermation> RolePermations { get; set; }
        public virtual DbSet<PersonalDataActorRole> PersonalDataActorRoles { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
    }
}
